### ISSUE TITLE
Speedyspeech loss

### ISSUE THREAD

**Issue by junkeon** [janvainer/speedyspeech#1]
Hi, this work is very impressive to me.

First of all, thanks to your work, paper and codes.

But i have a question about Speedyspeech loss.

According to the [paper](https://arxiv.org/pdf/2008.03802.pdf), speedyspeech use MAE and SSIM loss for logarithmic mel spectrogram
```
We use the sum of MAE and structural similarity index (SSIM) [12] losses for logarithmic mel spectrogram value regression 
```
but in codes, it uses MAE and SSIM loss for just output from decoder which is not logarithmic i guess.

I wonder why it does not use loss for logarithmic output.

Can you help me for this question?

thank you

**Comment by LordOfLuck** [comment]
Hi, thanks for the kind words and for a good question. :) The output from the decoder is trained to match normalized log transformed mel spectrograms. Once trained, the model therefore outputs similarly transformed spectrograms. If you want to feed the result eg. to griffin-lim, you have to 1) denormalize 2) exponentiate 3) invert mel to linear. Does that answer your question?

**Comment by junkeon** [comment]
Thank you for kind answer
i should have checked data loader but i didn't
thank you

**Comment by predawnang** [comment]
> Hi, thanks for the kind words and for a good question. :) The output from the decoder is trained to match normalized log transformed mel spectrograms. Once trained, the model therefore outputs similarly transformed spectrograms. If you want to feed the result eg. to griffin-lim, you have to 1) denormalize 2) exponentiate 3) invert mel to linear. Does that answer your question?

Hi, @janvainer. May I ask a question? when computing the SSIM between two log mel-spectorgrams as metric to evaluate sound quality of the synthetic audio(vocoder output), is it ok to directly input the log mel-spectorgrams to the SSIM (assume there's a function) without normalizing it?

**Comment by janvainer** [comment]
Its probably best if you can ensure the same volume/MVN normalization of your mels.
