### ISSUE TITLE
Why full connected layer replaced with conv1d？

### ISSUE THREAD

**Issue by superhg2012** [janvainer/speedyspeech#2]
Hi, I see that full connected layer descibed in paper are all replaced with conv1d layer ?  could you please explain that?

**Comment by janvainer** [comment]
Hi, Conv1D layer with kernel size 1 is equivalent to fully connected layer applied on each time frame. Does that answer your question?

**Comment by superhg2012** [comment]
> Hi, Conv1D layer with kernel size 1 is equivalent to fully connected layer applied on each time frame. Does that answer your question?

get it! conv1d saved more params too!
