### ISSUE TITLE
Should the teacher model predict next frame?

### ISSUE THREAD

**Issue by iclementine** [janvainer/speedyspeech#22]
I have a question about the teacher model (DurationExtractor).

As it is an autoregressive model, should it be targeted to predict the next frame? So the target is the input shifted by one time step. But I did not find something like this.

```python
spec_in = concat([start_frame, spec[:, :-1, :])
spec_target = spec
# model to predict the spec_out
l1loss = l1loss(spec_target, spec_out)
```

The main part in the training code is

```python
spectrs, slen, phonemes, plen, text = batch
s = add_random_noise(spectrs, hp.noise)
s = degrade_some(self, s, phonemes, plen, hp.feed_ratio, repeat=hp.feed_repeat)
s = frame_dropout(s, hp.replace_ratio)
out, att_weights = self.forward(phonemes, s, plen)

l1 = self.loss_l1(out, spectrs, slen)
```

Is it intended?
Thank you!

**Comment by janvainer** [comment]
Hi @iclementine, Thank you for your interest in SpeedySpeech. The shifting happens in the DuartionExtractor class (the teacher model).
See this [line](https://github.com/janvainer/speedyspeech/blob/3a30645249c9f60b9655626afbb263f3e43a4758/code/duration_extractor.py#L253) of code.

**Comment by iclementine** [comment]
> Hi @iclementine, Thank you for your interest in SpeedySpeech. The shifting happens in the DuartionExtractor class (the teacher model).
> See this [line](https://github.com/janvainer/speedyspeech/blob/3a30645249c9f60b9655626afbb263f3e43a4758/code/duration_extractor.py#L253) of code.

Oh, sorry, I did't noticed that.
