### ISSUE TITLE
trimming silences in the beginning and end of the audio

### ISSUE THREAD

**Issue by dsplog** [janvainer/speedyspeech#27]
@janvainer : from the code, did not see any logic for removing the potential silences in the beginning and end of the recording (in wave2spec() ) ? is it that it is not needed in this approach ?

**Comment by janvainer** [comment]
We used plain LJSpeech recordings without any trimming, since the dataset is quite clean. If your dataset contains silence, at the beginning or at the end, feel free to trim your audio.

**Comment by dsplog** [comment]
ah ok. closing
