### ISSUE TITLE
better than Tacotron2?

### ISSUE THREAD

**Issue by joan126** [janvainer/speedyspeech#4]
Anyone who compared this with Tacotron2 ? which one is better?

**Comment by LordOfLuck** [comment]
I compared audio quality with the public implementation of tacotron 2 by NVIDIA - see section 5. (Evaluation) of the [paper](https://arxiv.org/pdf/2008.03802.pdf).

**Comment by vladbataev** [comment]
Was the tacotron2 model trained on phoneme input?
