### ISSUE TITLE
does speedyspeech support transfer learning?

### ISSUE THREAD

**Issue by bespsm** [janvainer/speedyspeech#40]
Hi, I'm wondering if it possible after having already pretrained model continue training with another relatively smaller dataset? are some specific settings/adjustments required?

thanks.

**Comment by janvainer** [comment]
Hi, it is not supported out of the box, but you could create a copy of hte training script and implement loading from pretrained checkpoint and continuing training just like with regular pytorch model.

**Comment by bespsm** [comment]
thanks @janvainer
