### ISSUE TITLE
Positional encoding

### ISSUE THREAD

**Issue by VigneshBaskar** [janvainer/speedyspeech#46]
Hi Jan,

I think the function for position encoding is missing a bracket around (10.0**4). To be sure, I checked locally and the result varies without the bracket. Here is the current code snippet: https://github.com/janvainer/speedyspeech/blob/516eb1c6a992dacf5808e416c389e5322d9e80bf/code/functional.py#L31-L45
Can you please verify it and let me know? I shall fix it and open a PR. Thank you

Position encoding matrix **without** bracket
![image](https://user-images.githubusercontent.com/11005940/152683493-d01e06ed-1ff1-4ab8-823f-29438066cef7.png)

Position encoding matrix **with** bracket
![image](https://user-images.githubusercontent.com/11005940/152683550-d2207159-4f41-4377-8199-787f12d6ee19.png)

**Comment by janvainer** [comment]
Hi good catch, please use the develop branch where this issue is fixed, as discussed here: https://github.com/janvainer/speedyspeech/issues/23. Thanks! :)

**Comment by VigneshBaskar** [comment]
Thanks Jan. I will use the develop branch. Let me close this issue here.

**Comment by VigneshBaskar** [comment]
Hi Jan,
I have two question regarding this please:
1. The positional encoding is weighted and I see that keys are weighted by a hyperparameter `w` equaling 6.42 whereas the queries are weight 1. Can you please explain how did you choose this value? https://github.com/janvainer/speedyspeech/blob/c4e55478c6cb3251bb923f4062a8ab23ad83eed7/code/duration_extractor.py#L261-L263
https://github.com/janvainer/speedyspeech/blob/c4e55478c6cb3251bb923f4062a8ab23ad83eed7/code/hparam.py#L51-L53
2. Given that I am using the new positional encoding function from develop branch, any suggestion on what weight can I choose please?

My best guess with my current understanding is `w = num_spectrogram_frames / num_phonemes` (i.e.) average number of frames generated by a phoneme. But I am not sure.
Thank you very much
