### ISSUE TITLE
how to remove redundant silence in the synthesized wav

### ISSUE THREAD

**Issue by MorganCZY** [janvainer/speedyspeech#5]
Have you any ideas to remove the redundant silence at the end of every synthesized wav (mentioned at https://github.com/janvainer/speedyspeech/blob/2be09ef15a262a5f942c782311d3ed1070f22384/code/inference.py#L84)?

**Comment by LordOfLuck** [comment]
Hi, thanks for the interest in this repo. Yes, we have [durations available](https://github.com/janvainer/speedyspeech/blob/2be09ef15a262a5f942c782311d3ed1070f22384/code/inference.py#L73) and the sum of durations for the given utterance gives total count of final spectrogram frames. So we know how long the generated spectrograms are. All we need to know is how large upsampling is done by MelGan. So if you figure out how large is the upsampling factor from spectrograms to audio done by melgan. You can check the [MelGan repo](https://github.com/seungwonpark/melgan) and perhaps make an issue regarding this.

**Comment by MorganCZY** [comment]
I figured it out that the melgan has a 256x upsampling factor. Thus, I change the code as shown in the picture and have checked it works.
![image](https://user-images.githubusercontent.com/33675916/93302152-1868eb00-f82c-11ea-819e-f4ae2a986083.png)
Besides, it can be solved by synthesizing waves one by one undoubtedly. But I wanna learn about the comparison on time consumption of batched generation v.s. single item generation.

**Comment by janvainer** [comment]
Great! I hope you get the desired results. Closing the issue. Feel free to reopen if anything else is needed.
