### ISSUE TITLE
mismatch commits between master code and released speedyspeech.pth

### ISSUE THREAD

**Issue by MorganCZY** [janvainer/speedyspeech#6]
Hi, when running "m=SpeedySpeech(device=args.device).load(args.speedyspeech_checkpoint, map_location=args.device)", a warning occurs as shown bellow.
![image](https://user-images.githubusercontent.com/33675916/93305180-bfe81c80-f830-11ea-81e0-b7ffaae84541.png)
I'm on master with commit number 8a6c42b..., but I can't find where the commit 2fe23ad is.
btw, I downloaded the pretrained speedyspeech.pth from v2.0 released version.

**Comment by janvainer** [comment]
Hi, if the model works and returns legible audio, dont worry about it for now. I migrated the repo from another repository when releasing and the training commit was lost, probably when squishing commits. After that, there should not be any breaking code changes as I mainly updated the docs.

**Comment by MorganCZY** [comment]
ok, thx. Another question: I'm gonna train this repo on my own(still with LJSpeech). For the duration model, did you use the default params as shown in "duration_extractor.py"?

**Comment by janvainer** [comment]
yes I used the default params if I remember correctly.

**Comment by MorganCZY** [comment]
Thx. Hope I can get the same result as your model.
