### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by Moon-sung-woo** [janvainer/speedyspeech#7]
Hi! First of all, thank you for uploading the source code

When i try Train the duration extraction model, i had error at this code
-------------------------------------------------------------------------------------------------------
                spec = self.collate.norm.inverse(out[-1:]) # TODO: this fails if we do not standardize!
                sound, length = self.collate.stft.spec2wav(spec.transpose(1, 2), slen[-1:])

        torch.nn.utils.clip_grad_norm_(X, 1)
-------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/53896208/93331559-719c4300-f85b-11ea-9aa8-0ee51569723f.png)

Please give me solution

**Comment by janvainer** [comment]
Did you train with default settings or did you introduce some changes?

**Comment by Moon-sung-woo** [comment]
> Did you train with default settings or did you introduce some changes?

I trained defalut setting
Just changed git repo because of error

**Comment by janvainer** [comment]
What do you mean by changed repo?

**Comment by Moon-sung-woo** [comment]
> What do you mean by changed repo?

![image](https://user-images.githubusercontent.com/53896208/93354367-e3828580-f877-11ea-8353-de5c0fe47749.png)
Like this

**Comment by Moon-sung-woo** [comment]
> Did you train with default settings or did you introduce some changes?

I tried to original code, but i had same error TT
