### ISSUE TITLE
How to traini MelGAN

### ISSUE THREAD

**Issue by Moon-sung-woo** [janvainer/speedyspeech#8]
Hello, Thank you for your code
I finished training speedyspeech. So i want to train MelGAN for my dataset.
How can i train MelGAN?
please give me a solution.

**Comment by LordOfLuck** [comment]
Hi, you can use the pretrained melgan mentioned in README. If you want to train on custom data, please see the original MelGan repo linked from readme. It can be trained independently of SpeedySpeech.

**Comment by Moon-sung-woo** [comment]
If I use the melgens in this source code, can I use them with SpeedySpeech?

**Comment by LordOfLuck** [comment]
Yes, just follow the readme. You can use the model from this repo or train your own one based on the mentioned melgan repo.

**Comment by Moon-sung-woo** [comment]
Thank you very much
